-- Real supermarket catalog snapshots and append-only price history.
-- Writes are restricted to the service role through the ingestion RPC.

CREATE TABLE IF NOT EXISTS public.supermarket_scrape_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  requested_terms TEXT[] NOT NULL DEFAULT '{}',
  source_status JSONB NOT NULL DEFAULT '[]'::jsonb,
  product_count INTEGER NOT NULL DEFAULT 0 CHECK (product_count >= 0),
  status TEXT NOT NULL DEFAULT 'completed'
    CHECK (status IN ('completed', 'partial', 'failed')),
  fetched_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.supermarket_products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  store TEXT NOT NULL CHECK (store IN ('Jumbo', 'Santa Isabel', 'Lider', 'Unimarc')),
  source_product_key TEXT NOT NULL,
  last_query TEXT NOT NULL,
  name TEXT NOT NULL,
  brand TEXT,
  sku TEXT,
  ean TEXT,
  product_url TEXT,
  image_url TEXT,
  price INTEGER NOT NULL CHECK (price > 0),
  list_price INTEGER CHECK (list_price IS NULL OR list_price >= price),
  currency TEXT NOT NULL DEFAULT 'CLP' CHECK (currency = 'CLP'),
  in_stock BOOLEAN NOT NULL DEFAULT TRUE,
  first_seen_at TIMESTAMPTZ NOT NULL,
  last_seen_at TIMESTAMPTZ NOT NULL,
  last_run_id UUID REFERENCES public.supermarket_scrape_runs(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (store, source_product_key)
);

CREATE TABLE IF NOT EXISTS public.supermarket_price_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id UUID NOT NULL REFERENCES public.supermarket_products(id) ON DELETE CASCADE,
  run_id UUID NOT NULL REFERENCES public.supermarket_scrape_runs(id) ON DELETE CASCADE,
  query TEXT NOT NULL,
  price INTEGER NOT NULL CHECK (price > 0),
  list_price INTEGER CHECK (list_price IS NULL OR list_price >= price),
  in_stock BOOLEAN NOT NULL,
  observed_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (run_id, product_id, query)
);

ALTER TABLE public.supermarket_scrape_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supermarket_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supermarket_price_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS supermarket_runs_authenticated_read ON public.supermarket_scrape_runs;
CREATE POLICY supermarket_runs_authenticated_read
  ON public.supermarket_scrape_runs FOR SELECT TO authenticated
  USING (TRUE);

DROP POLICY IF EXISTS supermarket_products_authenticated_read ON public.supermarket_products;
CREATE POLICY supermarket_products_authenticated_read
  ON public.supermarket_products FOR SELECT TO authenticated
  USING (TRUE);

DROP POLICY IF EXISTS supermarket_history_authenticated_read ON public.supermarket_price_history;
CREATE POLICY supermarket_history_authenticated_read
  ON public.supermarket_price_history FOR SELECT TO authenticated
  USING (TRUE);

CREATE INDEX IF NOT EXISTS idx_supermarket_products_name
  ON public.supermarket_products USING gin (to_tsvector('spanish', name));
CREATE INDEX IF NOT EXISTS idx_supermarket_products_freshness
  ON public.supermarket_products(last_seen_at DESC) WHERE in_stock;
CREATE INDEX IF NOT EXISTS idx_supermarket_products_store_price
  ON public.supermarket_products(store, price) WHERE in_stock;
CREATE INDEX IF NOT EXISTS idx_supermarket_history_product_observed
  ON public.supermarket_price_history(product_id, observed_at DESC);

CREATE OR REPLACE FUNCTION public.ingest_supermarket_snapshot(
  p_terms TEXT[],
  p_products JSONB,
  p_source_status JSONB,
  p_fetched_at TIMESTAMPTZ
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_run_id UUID;
  v_product JSONB;
  v_product_id UUID;
  v_source_key TEXT;
  v_store TEXT;
  v_name TEXT;
  v_query TEXT;
  v_price INTEGER;
  v_list_price INTEGER;
  v_in_stock BOOLEAN;
  v_inserted INTEGER := 0;
  v_source_ok INTEGER := 0;
  v_source_total INTEGER := 0;
  v_run_status TEXT;
BEGIN
  IF jsonb_typeof(p_products) <> 'array' OR jsonb_typeof(p_source_status) <> 'array' THEN
    RAISE EXCEPTION 'products and source_status must be JSON arrays';
  END IF;

  SELECT
    count(*),
    count(*) FILTER (WHERE value->>'status' = 'ok')
  INTO v_source_total, v_source_ok
  FROM jsonb_array_elements(p_source_status);

  v_run_status := CASE
    WHEN v_source_ok = 0 THEN 'failed'
    WHEN v_source_ok < v_source_total THEN 'partial'
    ELSE 'completed'
  END;

  INSERT INTO public.supermarket_scrape_runs (
    requested_terms,
    source_status,
    product_count,
    status,
    fetched_at
  ) VALUES (
    COALESCE(p_terms, '{}'),
    p_source_status,
    jsonb_array_length(p_products),
    v_run_status,
    p_fetched_at
  )
  RETURNING id INTO v_run_id;

  FOR v_product IN SELECT value FROM jsonb_array_elements(p_products)
  LOOP
    v_store := NULLIF(btrim(v_product->>'store'), '');
    v_name := NULLIF(btrim(v_product->>'name'), '');
    v_query := COALESCE(NULLIF(btrim(v_product->>'query'), ''), 'catalogo');
    v_price := CASE
      WHEN COALESCE(v_product->>'price', '') ~ '^[0-9]+$' THEN (v_product->>'price')::INTEGER
      ELSE 0
    END;
    v_list_price := CASE
      WHEN COALESCE(v_product->>'list_price', '') ~ '^[0-9]+$' THEN (v_product->>'list_price')::INTEGER
      ELSE NULL
    END;
    v_in_stock := COALESCE((v_product->>'in_stock')::BOOLEAN, TRUE);
    v_source_key := left(COALESCE(
      NULLIF(btrim(v_product->>'sku'), ''),
      NULLIF(btrim(v_product->>'ean'), ''),
      NULLIF(btrim(v_product->>'product_url'), ''),
      lower(v_name)
    ), 1000);

    IF v_store NOT IN ('Jumbo', 'Santa Isabel', 'Lider', 'Unimarc')
      OR v_name IS NULL
      OR v_source_key IS NULL
      OR v_price <= 0 THEN
      CONTINUE;
    END IF;

    IF v_list_price IS NOT NULL AND v_list_price < v_price THEN
      v_list_price := NULL;
    END IF;

    INSERT INTO public.supermarket_products (
      store,
      source_product_key,
      last_query,
      name,
      brand,
      sku,
      ean,
      product_url,
      image_url,
      price,
      list_price,
      in_stock,
      first_seen_at,
      last_seen_at,
      last_run_id
    ) VALUES (
      v_store,
      v_source_key,
      v_query,
      v_name,
      NULLIF(btrim(v_product->>'brand'), ''),
      NULLIF(btrim(v_product->>'sku'), ''),
      NULLIF(btrim(v_product->>'ean'), ''),
      NULLIF(btrim(v_product->>'product_url'), ''),
      NULLIF(btrim(v_product->>'image_url'), ''),
      v_price,
      v_list_price,
      v_in_stock,
      p_fetched_at,
      p_fetched_at,
      v_run_id
    )
    ON CONFLICT (store, source_product_key) DO UPDATE SET
      last_query = EXCLUDED.last_query,
      name = EXCLUDED.name,
      brand = EXCLUDED.brand,
      sku = EXCLUDED.sku,
      ean = EXCLUDED.ean,
      product_url = EXCLUDED.product_url,
      image_url = EXCLUDED.image_url,
      price = EXCLUDED.price,
      list_price = EXCLUDED.list_price,
      in_stock = EXCLUDED.in_stock,
      last_seen_at = EXCLUDED.last_seen_at,
      last_run_id = EXCLUDED.last_run_id,
      updated_at = NOW()
    RETURNING id INTO v_product_id;

    INSERT INTO public.supermarket_price_history (
      product_id,
      run_id,
      query,
      price,
      list_price,
      in_stock,
      observed_at
    ) VALUES (
      v_product_id,
      v_run_id,
      v_query,
      v_price,
      v_list_price,
      v_in_stock,
      p_fetched_at
    )
    ON CONFLICT (run_id, product_id, query) DO NOTHING;

    v_inserted := v_inserted + 1;
  END LOOP;

  UPDATE public.supermarket_scrape_runs
  SET product_count = v_inserted
  WHERE id = v_run_id;

  RETURN jsonb_build_object(
    'run_id', v_run_id,
    'status', v_run_status,
    'product_count', v_inserted,
    'fetched_at', p_fetched_at
  );
END;
$$;

REVOKE ALL ON FUNCTION public.ingest_supermarket_snapshot(TEXT[], JSONB, JSONB, TIMESTAMPTZ) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ingest_supermarket_snapshot(TEXT[], JSONB, JSONB, TIMESTAMPTZ) FROM anon;
REVOKE ALL ON FUNCTION public.ingest_supermarket_snapshot(TEXT[], JSONB, JSONB, TIMESTAMPTZ) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.ingest_supermarket_snapshot(TEXT[], JSONB, JSONB, TIMESTAMPTZ) TO service_role;
